In [26]:
import numpy as np

P1 = 0.49
P2 = 0.38
P3 = 0.1
P4 = 0.03

2 * (P1 * P2 + P1 * P3 + P1 * P4 + P2 * P3 + P2 * P4 + P3 * P4) + P1 * P1 + P2 * P2 + P3 * P3 + P4 * P4

a = np.array([[P1 * P1, P1 * P2, P1 * P3, P1 * P4],
              [P2 * P1, P2 * P2, P2 * P3, P2 * P4],
              [P3 * P1, P3 * P2, P3 * P3, P3 * P4],
              [P4 * P1, P4 * P2, P4 * P3, P4 * P4]])
print a


print a[0,0] + a[1,0] + a[2,0] + a[3,0] + a[1,1] + a[3,1] + a[2,2] + a[2,3] + a[3,3]
PAB1 = P1 + P2 + P3 + P4
PAB2 = P2 + P4
PAB3 = P3 + P4
PAB4 = P4
P1 * PAB1 + P2 * PAB2 + P3 * PAB3 + P4 * PAB4



[[ 0.2401  0.1862  0.049   0.0147]
 [ 0.1862  0.1444  0.038   0.0114]
 [ 0.049   0.038   0.01    0.003 ]
 [ 0.0147  0.0114  0.003   0.0009]]
0.2401
0.1862
0.049
0.0147
0.1444
0.0114
0.6597


0.6597000000000001